pipeline {
    agent { label 'agent-node-01-build' }
    stages {
        stage('Build') { 
            steps {
                sh 'echo Hello-World' 
            }
        }
        stage('Test') { 
            steps {
                sh 'echo This-is-Test-step'     
            }
        }
        stage('Deploy') { 
            steps {
                sh 'echo This-is-Deploy-step'
            }
        }
    }
}